obstacle_range: 2.5 #2.5
raytrace_range: 3.0 #3.0
footprint: [[-0.12, -0.14], [-0.12, 0.14], [0.12, 0.14], [0.12, -0.14]]
inflation_radius: 0.75
transform_tolerance: 0.5
#lethal_cost_threshold: 100
use_dijkstra: True
use_quadratic: True 

observation_sources: scan
scan:
  sensor_frame: ebot_base
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true
map_type: costmap
