global_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 5.0 #before: 1.0
  publish_frequency: 2.0 #before 0.5
  static_map: true
  transform_tolerance: 0.5
  cost_scaling_factor: 12.0
  inflation_radius: 0.55 #0.25 #0.55
  footprint_padding: 0.02

