TrajectoryPlannerROS:
  max_vel_x: 0.2 #-.5
  min_vel_x: -0.1 #0.01/2  
  max_vel_theta: 0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.6
  acc_lim_theta: 2.2
  acc_lim_x: 1.5
  acc_lim_y: 1.5
  holonomic_robot: false
  meter_scoring: true
  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.35
  